minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@k8o/*'
  # Renovate security update: pnpm@11.8.0
  - pnpm@11.8.0

blockExoticSubdeps: true
verifyDepsBeforeRun: install
savePrefix: ''

allowBuilds:
  esbuild: false
