name: Install
description: Sets up mise and runs install

runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        cache: true

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build
      shell: bash
      run: pnpm build
