name: Install
description: Sets up mise and runs install

runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      with:
        cache: true

    - name: Install dependencies
      shell: bash
      run: pnpm ci

    - name: Build
      shell: bash
      run: pnpm build
