name: Install
description: Sets up mise and runs install

runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
      with:
        cache: true

    - name: Install dependencies
      shell: bash
      run: pnpm ci

    - name: Build
      shell: bash
      run: pnpm build
